[package]
name = "finescale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot = "0.1.4"
iced = { version = "0.9.0", features = ["svg"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
