[package]
name = "finescale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
iced = { version = "0.9.0", features = ["svg"] }
petgraph = "0.6.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

[workspace]
members = ["scraper"]
